### ISSUE TITLE
Change radius of how far away it shows the prompt help notification.

### ISSUE THREAD

**Issue by aler1337** [Lachee/fivem-garage#1]
Hey!

Really loving the garage script, altough I have a question.

How does one change the radius of how far away the marker shows for, and how far away do you have to be for the help notification to appear/disappear.
Don't really like the way the players need to be really close to show the marker, and really far for the help notification to disappear.

**Comment by Lachee** [comment]
Added a configuration for the draw distance to the garage. 
The interaction distance is based of the mareker size which is either 4m or 1.5m depending if the user is in a vehicle or not.
