### ISSUE TITLE
Vehicles not showing....

### ISSUE THREAD

**Issue by stoyanovx** [Lachee/fivem-garage#2]
When I buy vehicle ,the vehicle is database ,everything seems okay , but when I open the "Parked Vehicles" or "Vehicle Recovery" nothing pop up. After little investigating , the problem is in the database. The sql file  -> initial.sql , have a wrong sql query. //`owner` varchar(22) COLLATE utf8mb4_bin NOT NULL, //. Change varchar(22) to varchar(255).

**Comment by Lachee** [comment]
All fixed!
